### ISSUE TITLE
User can see top currently airing anime

### ISSUE THREAD

**Issue by shawnkost** [shawnkost/ajax-project#3]
## Feature
User can see top anime of all time

## 📐 Plan

Create a basic webpage that shows the top airing animes

## 🖼️ Wireframe

![image](https://user-images.githubusercontent.com/71413368/102267039-2f23ea00-3ece-11eb-9d73-91c118c8e0a5.png)

## ✅ Task List
- [x] Create a row for the top airing anime of all time that includes a heading and empty image containers.
- [x] Declare a javascript function that makes a network request to Jikan API.  
- [x] Using the data from the network request, update the image src's to show the image url.
- [x] Use CSS to make the top airing anime row look polished
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again.
