### ISSUE TITLE
Show anime page with details about show

### ISSUE THREAD

**Issue by shawnkost** [shawnkost/ajax-project#4]
## Feature
User can see top anime of all time

## 📐 Plan

Create a basic webpage that shows the details of the anime page.

## 🖼️ Wireframe
![image](https://user-images.githubusercontent.com/71413368/102294785-e0427880-3efe-11eb-82e2-795d816628f2.png)

## ✅ Task List
- [x] Build an example info page in HTML.
- [x] Declare a view swapping function that shows the info page. 
- [x] Add an event listener that shows the details data-view when an image is clicked.
- [x] Declare a function that receives data from the API and replaces the HTML content from the current anime image that was clicked.
- [x] Embed youtube video to end of page
- [x] Adjust CSS to make page look polished
- [x] Check functionality
