### ISSUE TITLE
User can view MAL

### ISSUE THREAD

**Issue by shawnkost** [shawnkost/ajax-project#5]
## Feature
User can see their MAL

## 📐 Plan

Create a basic webpage that shows the users MAL

## 🖼️ Wireframe
![image](https://user-images.githubusercontent.com/71413368/102399444-804ae100-3f95-11eb-928f-a1deabb6be59.png)

## ✅ Task List
- [x] Remove important from hidden in CSS.
- [x] Build an example list table in HTML.
- [x] Update the viewSwap function to take us to the list data-view when list is clicked.
- [x] Create a DOM Tree in JS that mimics the one we created in HTML.
- [x] Input the data from API into the newly created dom tree.
- [x] Adjust CSS to match the list to the wireframe.
- [x] Check functionality.
- [x] Bug fix.
- [x] Check that all code is needed.
