### ISSUE TITLE
User can search for anime

### ISSUE THREAD

**Issue by shawnkost** [shawnkost/ajax-project#6]
## Feature
User can search for animes

## 📐 Plan

Add search functionality to find a specific anime

## 🖼️ Wireframe
![image](https://user-images.githubusercontent.com/71413368/102399444-804ae100-3f95-11eb-928f-a1deabb6be59.png)

## ✅ Task List

- [x] Add an icon to the search bar.
- [x] Add an event listener to the icon/input to submit the text.
- [x] Take user input and call it on API to return results.
- [x] Fix search icon.
- [x] Add functionality so enter searches the result.
- [x] Adjust CSS.
